### ISSUE TITLE
uber-naked theme folder there is no "rebase-min.css" file

### ISSUE THREAD

**Issue by peraburek** [UberGallery/uber-naked#1]
https://github.com/UberGallery/uber-naked/blob/master/index.php

in uber-naked theme folder there is NO "rebase-min.css" file, so you could remove this line

 <link rel="stylesheet" type="text/css" href="<?php echo THEMEPATH; ?>/rebase-min.css" />

from index.php in uber-naked

**Comment by PHLAK** [comment]
Resolved with commit 66b06bd66e46f6dd43e69d6ba9e1b3626d6446f5
